### ISSUE TITLE
Deploy app to Vercel

### ISSUE THREAD

**Issue by rawat9** [rawat9/the-project#5]
- Think of the product name
- Setup email account & share with the team
- Deploy!!

**Comment by rawat9** [comment]
@pedrocor12 Please make sure you discuss the chosen brand name with the Team first

**Comment by pedrocor12** [comment]
Dragfolio - Possible brand name (Drag and drop with portfolio ), and the name is not taken as a domain i believe.

**Comment by rawat9** [comment]
"Dnd w/ portfolio" isn't the tagline I would choose as that's not this product's USP. Maybe try something along the lines of:

- "personalised portfolio creation tool"
- "showcase your skills/work/projects to employers/recruiters"

cc @daryl-micah @ananyachibber21

**Comment by pedrocor12** [comment]
When naming a product, it's crucial to keep the name concise and memorable. A single word or a very short phrase often works best because it's easy for customers to recall and it stands out in marketing materials and conversations. Using a longer phrase as a product name can complicate marketing efforts, making it harder for the name to stick in the consumer's mind. It can also create challenges in branding, as longer phrases are difficult to incorporate into logos and packaging. Furthermore, a succinct name can have a strong impact across various platforms, especially on social media where brevity is essential. Consider successful brands like Apple, Nike, or Tesla — each uses a short, distinct name that embodies the brand and is easily recognizable. This is why it’s generally better to reserve longer descriptions for marketing copy where you can elaborate on the product's features and benefits, rather than in the name itself.

**Comment by rawat9** [comment]
What are you trying to imply? Can you give at least a few (5-10) options and we can further shortlist?

**Comment by daryl-micah** [comment]
> When naming a product, it's crucial to keep the name concise and memorable. A single word or a very short phrase often works best because it's easy for customers to recall and it stands out in marketing materials and conversations. Using a longer phrase as a product name can complicate marketing efforts, making it harder for the name to stick in the consumer's mind. It can also create challenges in branding, as longer phrases are difficult to incorporate into logos and packaging. Furthermore, a succinct name can have a strong impact across various platforms, especially on social media where brevity is essential. Consider successful brands like Apple, Nike, or Tesla — each uses a short, distinct name that embodies the brand and is easily recognizable. This is why it’s generally better to reserve longer descriptions for marketing copy where you can elaborate on the product's features and benefits, rather than in the name itself.

This looks like some quality chatGPT stuff... (kidding 😆)
"Dragfolio" is a good effort but I think the name is a little weird to pronounce.

**Comment by rawat9** [comment]
Deployed here - [expose-project.vercel.app](https://expose-project.vercel.app/)

**Comment by pedrocor12** [comment]
Initial Deployment has been completed guys , and the details for the password and email for the account are present on the teams chat , if you would like to login to vercel look at the project team chat.
